doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        types:
            enum: App\CustomType\Enum
            point: App\CustomType\Point
            polygon: App\CustomType\Polygon
            set: App\CustomType\Set

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Sky:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity/Sky'
                prefix: 'App\Entity\Sky'
                alias: Sky
